services:
  bristlecone-engine:
    container_name: bristlecone_m2m_engine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - API_KEY=bristlecone-dev-key
