"""create_commit_dag_and_invigilator_tables

Revision ID: c87fd150ac08
Revises: ff4c314d8ff1
Create Date: 2026-07-28 13:21:49.242071
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c87fd150ac08'
down_revision: Union[str, None] = 'ff4c314d8ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
