"""add_commit_dag_and_invigilator_tables

Revision ID: ff4c314d8ff1
Revises: 3db8dfc6c72e
Create Date: 2026-07-28 13:18:59.577994
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ff4c314d8ff1'
down_revision: Union[str, None] = '3db8dfc6c72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
