from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, ConfigDict, Field

class TaskType(str, Enum):
    DATA_CLEANING = "data_cleaning"
    SYSTEM_INSPECTION = "system_inspection"
    TRANSFORMATION = "transformation"

class TaskPriority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

class TaskExecutionRequest(BaseModel):
    # Enforce strict parsing: reject payloads with unexpected hallucinated keys
    model_config = ConfigDict(extra="forbid")

    task_id: str = Field(..., description="Unique UUID or identifier generated by the requesting agent")
    task_type: TaskType = Field(..., description="Category of execution routine")
    priority: TaskPriority = Field(default=TaskPriority.MEDIUM, description="Queue priority level")
    payload: Dict[str, Any] = Field(..., description="Parameters required by the specific microservice routine")
    timeout_seconds: Optional[int] = Field(default=30, ge=1, le=300, description="Max execution window in seconds")

class TaskExecutionResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    task_id: str
    status: str
    execution_time_ms: float
    result: Dict[str, Any]
    error: Optional[str] = None
from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, ConfigDict, Field

class TaskType(str, Enum):
    DATA_CLEANING = "data_cleaning"
    SYSTEM_INSPECTION = "system_inspection"
    TRANSFORMATION = "transformation"

class TaskPriority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

class TaskExecutionRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    task_id: str = Field(..., description="Unique UUID or identifier generated by requesting agent")
    task_type: TaskType = Field(..., description="Category of execution routine")
    priority: TaskPriority = Field(default=TaskPriority.MEDIUM, description="Queue priority level")
    payload: Dict[str, Any] = Field(..., description="Parameters required by specific microservice routine")
    signature: str = Field(..., description="Layer 4 HMAC-SHA256 signature verifying Invigilator approval")
    timeout_seconds: Optional[int] = Field(default=30, ge=1, le=300, description="Max execution window in seconds")

class TaskExecutionResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    task_id: str
    status: str
    execution_time_ms: float
    result: Dict[str, Any]
    error: Optional[str] = None
